import pandas as pd
from scipy.io import arff
data=arff.loadarff('./ElectricDevices/ElectricDevices_TEST.arff')
df=pd.DataFrame(data[0])
data1=arff.loadarff('./ElectricDevices/ElectricDevices_TRAIN.arff')
df1=pd.DataFrame(data[0])
df=df.replace(b'1',1)
df=df.replace(b'2',2)
df1=df1.replace(b'1',1)
df1=df1.replace(b'2',2)
df=df.replace(b'3',3)
df=df.replace(b'4',4)
df1=df1.replace(b'3',3)
df1=df1.replace(b'4',4)
df=df.replace(b'5',5)
df=df.replace(b'6',6)
df1=df1.replace(b'5',5)
df1=df1.replace(b'6',6)
df=df.replace(b'7',7)
df1=df1.replace(b'7',7)
df.to_csv('./ElectricDevices/ElectricDevices_TEST.csv',header=False,index=False)
df1.to_csv('./ElectricDevices/ElectricDevices_TRAIN.csv',header=False,index=False)